<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MyTestPackage"
    nsURI="http://www.mytest.com" nsPrefix="test">
  <eClassifiers xsi:type="ecore:EClass" name="ClassA" eSuperTypes="#//MyTestSubPackage/ClassSubA #//MyTestSubPackage2/ClassSub2A"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassB" eSuperTypes="#//ClassA"/>
  <eSubpackages name="MyTestSubPackage" nsURI="http://www.mysubtest.com" nsPrefix="subtest">
    <eClassifiers xsi:type="ecore:EClass" name="ClassSubA"/>
  </eSubpackages>
  <eSubpackages name="MyTestSubPackage2" nsURI="http://www.mysubtest2.com" nsPrefix="subtest2">
    <eClassifiers xsi:type="ecore:EClass" name="ClassSub2A"/>
  </eSubpackages>
</ecore:EPackage>
